# This file was generated by GoReleaser. DO NOT EDIT.
cask "counterpoint" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "69eecb8aabda80ddbc07a9cf76f00a3d0818cd1cbac659676635d3175bbb7422"
      url "https://github.com/SnapdragonPartners/counterpoint/releases/download/v#{version}/counterpoint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1dc9f66800664a6484781a064309da4bee16d4cac16f89a22cdc55e967c7c2aa"
      url "https://github.com/SnapdragonPartners/counterpoint/releases/download/v#{version}/counterpoint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa5783d7b77727260ecd6d8f602257aed0b1ae8d0c64a5887ebabdb8a5cd99a3"
      url "https://github.com/SnapdragonPartners/counterpoint/releases/download/v#{version}/counterpoint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "71a4ab88b1fbc939c71d4ef7dcf4ed6edb24b186a974d581ea4273ae6eb27f10"
      url "https://github.com/SnapdragonPartners/counterpoint/releases/download/v#{version}/counterpoint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "counterpoint"
  desc "MCP server that hands a coding agent's commits to a persistent Codex reviewer"
  homepage "https://github.com/SnapdragonPartners/counterpoint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "counterpoint"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/counterpoint"]
    end
  end

  # No zap stanza required
end
