# This file was generated by GoReleaser. DO NOT EDIT.
cask "maestro" do
  version "1.3.9"

  on_macos do
    on_intel do
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_darwin_amd64.zip"
      sha256 "168e00ff66d31ba7cd906bacf5489112f876a711512cfee0d162fa499786c42e"
    end
    on_arm do
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_darwin_arm64.zip"
      sha256 "0fdace630280ebfcdda2884a5aca3b8d4a74bdf2a26f4c26ba0b8351596d27ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_linux_amd64.tar.gz"
      sha256 "21039628bd672400867594ef1521b35920045833793133e23110c484c228abd5"
    end
    on_arm do
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_linux_arm64.tar.gz"
      sha256 "10173c82cf60f9a6a71f463797fd5fc7fa2ffb27fc5aa84e6d4acb7b567ba884"
    end
  end

  name "maestro"
  desc "Multi-agent AI coding system orchestrator"
  homepage "https://github.com/SnapdragonPartners/maestro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maestro"

  # No zap stanza required

end
