# This file was generated by GoReleaser. DO NOT EDIT.
cask "maestro" do
  version "1-freeze"

  on_macos do
    on_intel do
      sha256 "30a7b59621988c63e81d3cb20ac6fd5c72fdafc50a4b3d96bad84fafd8db8755"
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "386c72c896830dec4d53ad290d0537e3cb12c4c2a06b9c9d4089054d0e93d169"
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "285262c619c85c6e3be1e72a3d3f3d3f210dc425cd713c3449103f7b5dd20fd5"
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a281b5b80f933865f5cb9a07569887c1890a8b5fa9568ec02f9e6ad680bfaad"
      url "https://github.com/SnapdragonPartners/maestro/releases/download/v#{version}/maestro_#{version}_linux_arm64.tar.gz"
    end
  end

  name "maestro"
  desc "Multi-agent AI coding system orchestrator"
  homepage "https://github.com/SnapdragonPartners/maestro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "maestro"

  # No zap stanza required

end
